stages:
  - build
  - test
  
default:
  name: pipeline2
  docker:
    registry: docker.io
    image: openjdk:17-jdk-slim
  
checkout:
  stage: build
  script: 
    - echo "Checkout"
build:
  stage: build
  needs: ["checkout"]
  script: 
    - echo "Building"
test:
  stage: test
  script: 
    - echo "Testing"
start:
  stage: build
  needs: ["build"]
  script:
    - echo "Start"
end:
  stage: build
  needs: ["build"]
  script:
    - echo "end"